USE [master]
GO

/****** Object:  Database [MyFace]    Script Date: 11/9/2017 4:26:58 PM ******/
CREATE DATABASE [MyFace]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyFace', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.KMURPHYLOCALSQL\MSSQL\DATA\MyFace.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MyFace_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.KMURPHYLOCALSQL\MSSQL\DATA\MyFace_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MyFace] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyFace].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyFace] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyFace] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyFace] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyFace] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyFace] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyFace] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyFace] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyFace] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyFace] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyFace] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyFace] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyFace] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyFace] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyFace] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyFace] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyFace] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyFace] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyFace] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyFace] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyFace] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyFace] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyFace] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyFace] SET RECOVERY FULL 
GO

ALTER DATABASE [MyFace] SET  MULTI_USER 
GO

ALTER DATABASE [MyFace] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyFace] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyFace] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyFace] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MyFace] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyFace] SET  READ_WRITE 
GO

