//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFaceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Posts = new HashSet<Post>();
            this.Users1 = new HashSet<User>();
            this.Users = new HashSet<User>();
        }
    
        public int userId { get; set; }
        public string realName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public byte[] image { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string zodiacSign { get; set; }
        public string address1 { get; set; }
        public string adress2 { get; set; }
        public string phoneNumber { get; set; }
        public string prefferedSSN { get; set; }
        public string description { get; set; }
        public Nullable<bool> isMaleGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }

	}
}
