//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFaceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFriend
    {
        public int pkId { get; set; }
        public int userId { get; set; }
        public int friendId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
